name: Act on release created

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          export GITHUB_USERNAME=${{ secrets.GIT_USER }}
          export GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build aar
        run: |
          chmod +x gradlew
          ./gradlew build pronto:assemble
          ./gradlew publish
